// Generated by scripts/build-supabase-api.mjs. Do not edit.
import h_set_catalog from "./set-catalog.js";
import h_master_set from "./master-set.js";
import h_legacy_card_search from "./legacy-card-search.js";
import h_jp_card_search from "./jp-card-search.js";
import h_limitless_variants from "./limitless-variants.js";
import h_card_image_fallback from "./card-image-fallback.js";
import h_image_proxy from "./image-proxy.js";
import h_tcgdex_card_image from "./tcgdex-card-image.js";
import h_jp_card_image from "./jp-card-image.js";
import h_limitless_image from "./limitless-image.js";
import h_poketrack_image from "./poketrack-image.js";
export const HANDLERS = {
  "set-catalog": h_set_catalog,
  "master-set": h_master_set,
  "legacy-card-search": h_legacy_card_search,
  "jp-card-search": h_jp_card_search,
  "limitless-variants": h_limitless_variants,
  "card-image-fallback": h_card_image_fallback,
  "image-proxy": h_image_proxy,
  "tcgdex-card-image": h_tcgdex_card_image,
  "jp-card-image": h_jp_card_image,
  "limitless-image": h_limitless_image,
  "poketrack-image": h_poketrack_image,
};
export const IMAGE_HANDLERS = new Set(["image-proxy","tcgdex-card-image","jp-card-image","limitless-image","poketrack-image"]);
export const BROWSER_HANDLERS = new Set(["myp-search","myp-catalog-public","myp-related-catalog","mypcards-public","mypcards","liga-public","price-engine"]);
